version: '3.4'

services:
  document-analyser-api:
    image: ${DOCKER_REGISTRY-}documentanalyserapi
    build:
      context: .
      dockerfile: Document-Analyser-Api/Dockerfile
    container_name: document-analyser-api
